<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Docker and Docker Compose – CSE312 Lectures</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
.display.math{display: block; text-align: center; margin: 0.5rem auto;}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-c8ad9e5dbd60b7b70b38521ab19b7da4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-4c57cdd5e80f6ca436998ce64738895a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
</head><body class="quarto-light"><a class="skip-link" href="#main-content">Skip to main content</a>
<script>
document.addEventListener("DOMContentLoaded", function () {
  if (document.getElementById("main-content")) {
    return;
  }
  var target =
    document.querySelector(".reveal .slides") ||
    document.getElementById("quarto-document-content") ||
    document.querySelector("main");
  if (target) {
    target.id = "main-content";
  }
});
</script>






<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#docker-and-docker-compose" id="toc-docker-and-docker-compose" class="nav-link active" data-scroll-target="#docker-and-docker-compose">Docker and docker compose</a></li>
  <li><a href="#vocab" id="toc-vocab" class="nav-link" data-scroll-target="#vocab">Vocab</a></li>
  <li><a href="#deployment-headaches" id="toc-deployment-headaches" class="nav-link" data-scroll-target="#deployment-headaches">Deployment Headaches</a></li>
  <li><a href="#virtual-machines" id="toc-virtual-machines" class="nav-link" data-scroll-target="#virtual-machines">Virtual Machines</a></li>
  <li><a href="#security" id="toc-security" class="nav-link" data-scroll-target="#security">Security</a></li>
  <li><a href="#security-1" id="toc-security-1" class="nav-link" data-scroll-target="#security-1">Security</a></li>
  <li><a href="#containers" id="toc-containers" class="nav-link" data-scroll-target="#containers">Containers</a></li>
  <li><a href="#docker" id="toc-docker" class="nav-link" data-scroll-target="#docker">Docker</a></li>
  <li><a href="#dockerfile" id="toc-dockerfile" class="nav-link" data-scroll-target="#dockerfile">Dockerfile</a></li>
  <li><a href="#dockerfile-1" id="toc-dockerfile-1" class="nav-link" data-scroll-target="#dockerfile-1">Dockerfile</a></li>
  <li><a href="#run-the-app" id="toc-run-the-app" class="nav-link" data-scroll-target="#run-the-app">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-2" id="toc-dockerfile-2" class="nav-link" data-scroll-target="#dockerfile-2">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-1" id="toc-run-the-app-1" class="nav-link" data-scroll-target="#run-the-app-1">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-3" id="toc-dockerfile-3" class="nav-link" data-scroll-target="#dockerfile-3">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-2" id="toc-run-the-app-2" class="nav-link" data-scroll-target="#run-the-app-2">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-4" id="toc-dockerfile-4" class="nav-link" data-scroll-target="#dockerfile-4">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-3" id="toc-run-the-app-3" class="nav-link" data-scroll-target="#run-the-app-3">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-5" id="toc-dockerfile-5" class="nav-link" data-scroll-target="#dockerfile-5">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-4" id="toc-run-the-app-4" class="nav-link" data-scroll-target="#run-the-app-4">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-6" id="toc-dockerfile-6" class="nav-link" data-scroll-target="#dockerfile-6">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-5" id="toc-run-the-app-5" class="nav-link" data-scroll-target="#run-the-app-5">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-7" id="toc-dockerfile-7" class="nav-link" data-scroll-target="#dockerfile-7">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-6" id="toc-run-the-app-6" class="nav-link" data-scroll-target="#run-the-app-6">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-8" id="toc-dockerfile-8" class="nav-link" data-scroll-target="#dockerfile-8">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-7" id="toc-run-the-app-7" class="nav-link" data-scroll-target="#run-the-app-7">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-9" id="toc-dockerfile-9" class="nav-link" data-scroll-target="#dockerfile-9">Dockerfile</a></li>
  </ul></li>
  <li><a href="#run-the-app-8" id="toc-run-the-app-8" class="nav-link" data-scroll-target="#run-the-app-8">Run the app</a>
  <ul class="collapse">
  <li><a href="#dockerfile-10" id="toc-dockerfile-10" class="nav-link" data-scroll-target="#dockerfile-10">Dockerfile</a></li>
  <li><a href="#dockerfile-11" id="toc-dockerfile-11" class="nav-link" data-scroll-target="#dockerfile-11">Dockerfile</a></li>
  <li><a href="#dockerfile-12" id="toc-dockerfile-12" class="nav-link" data-scroll-target="#dockerfile-12">Dockerfile</a></li>
  <li><a href="#running-your-app" id="toc-running-your-app" class="nav-link" data-scroll-target="#running-your-app">Running Your App</a></li>
  <li><a href="#docker-compose" id="toc-docker-compose" class="nav-link" data-scroll-target="#docker-compose">Docker Compose</a></li>
  <li><a href="#docker-compose-1" id="toc-docker-compose-1" class="nav-link" data-scroll-target="#docker-compose-1">Docker Compose</a></li>
  <li><a href="#docker-compose-2" id="toc-docker-compose-2" class="nav-link" data-scroll-target="#docker-compose-2">Docker Compose</a></li>
  <li><a href="#docker-compose-3" id="toc-docker-compose-3" class="nav-link" data-scroll-target="#docker-compose-3">Docker Compose</a></li>
  <li><a href="#docker-compose-4" id="toc-docker-compose-4" class="nav-link" data-scroll-target="#docker-compose-4">Docker Compose</a></li>
  <li><a href="#docker-compose-5" id="toc-docker-compose-5" class="nav-link" data-scroll-target="#docker-compose-5">Docker Compose</a></li>
  <li><a href="#docker-compose-6" id="toc-docker-compose-6" class="nav-link" data-scroll-target="#docker-compose-6">Docker Compose</a></li>
  <li><a href="#docker-compose-7" id="toc-docker-compose-7" class="nav-link" data-scroll-target="#docker-compose-7">Docker Compose</a></li>
  <li><a href="#docker-compose-8" id="toc-docker-compose-8" class="nav-link" data-scroll-target="#docker-compose-8">Docker Compose</a></li>
  <li><a href="#running-your-app-1" id="toc-running-your-app-1" class="nav-link" data-scroll-target="#running-your-app-1">Running Your App</a></li>
  <li><a href="#running-your-app-2" id="toc-running-your-app-2" class="nav-link" data-scroll-target="#running-your-app-2">Running Your App</a></li>
  <li><a href="#docker-compose-9" id="toc-docker-compose-9" class="nav-link" data-scroll-target="#docker-compose-9">Docker Compose</a></li>
  <li><a href="#docker-compose-10" id="toc-docker-compose-10" class="nav-link" data-scroll-target="#docker-compose-10">Docker Compose</a></li>
  <li><a href="#docker-compose-11" id="toc-docker-compose-11" class="nav-link" data-scroll-target="#docker-compose-11">Docker Compose</a></li>
  <li><a href="#docker-compose-12" id="toc-docker-compose-12" class="nav-link" data-scroll-target="#docker-compose-12">Docker Compose</a></li>
  <li><a href="#docker-compose-13" id="toc-docker-compose-13" class="nav-link" data-scroll-target="#docker-compose-13">Docker Compose</a></li>
  <li><a href="#docker-compose-14" id="toc-docker-compose-14" class="nav-link" data-scroll-target="#docker-compose-14">Docker Compose</a></li>
  <li><a href="#docker-compose-15" id="toc-docker-compose-15" class="nav-link" data-scroll-target="#docker-compose-15">Docker Compose</a></li>
  <li><a href="#docker-compose-16" id="toc-docker-compose-16" class="nav-link" data-scroll-target="#docker-compose-16">Docker Compose</a></li>
  <li><a href="#docker-compose-17" id="toc-docker-compose-17" class="nav-link" data-scroll-target="#docker-compose-17">Docker Compose</a></li>
  <li><a href="#docker-compose-18" id="toc-docker-compose-18" class="nav-link" data-scroll-target="#docker-compose-18">Docker Compose</a></li>
  <li><a href="#docker-compose-19" id="toc-docker-compose-19" class="nav-link" data-scroll-target="#docker-compose-19">Docker Compose</a></li>
  <li><a href="#docker-compose-20" id="toc-docker-compose-20" class="nav-link" data-scroll-target="#docker-compose-20">Docker Compose</a></li>
  <li><a href="#running-your-app-3" id="toc-running-your-app-3" class="nav-link" data-scroll-target="#running-your-app-3">Running Your App</a></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading">Further Reading</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Docker and Docker Compose</h1>
<p class="subtitle lead">CSE312 — Web Development</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="docker-and-docker-compose" class="level2">
<h2 class="anchored" data-anchor-id="docker-and-docker-compose">Docker and docker compose</h2>
<p>1</p>
</section>
<section id="vocab" class="level2">
<h2 class="anchored" data-anchor-id="vocab">Vocab</h2>
<ul>
<li>Development Environment (dev)
<ul>
<li>The environment where you write your code</li>
<li>Ex. Your laptop</li>
<li>Add features; Find and eliminate bugs</li>
</ul></li>
<li>Production environment (prod)
<ul>
<li>The environment where your app will eventually live</li>
<li>The live server with real end users</li>
<li>Do everything we can to avoid bugs in production</li>
</ul></li>
</ul>
<p>2</p>
</section>
<section id="deployment-headaches" class="level2">
<h2 class="anchored" data-anchor-id="deployment-headaches">Deployment Headaches</h2>
<ul>
<li>It works on my laptop!</li>
<li>Run your code in production and it’s broken</li>
<li>Many causes
<ul>
<li>Different version of compiler/interpreter</li>
<li>Dependancies not linked</li>
<li>Hard-coded paths</li>
<li>Different environment variables</li>
<li>etc.</li>
</ul></li>
</ul>
<p>3</p>
</section>
<section id="virtual-machines" class="level2">
<h2 class="anchored" data-anchor-id="virtual-machines">Virtual Machines</h2>
<ul>
<li>Simulate an entire machine</li>
<li>Run the virtual machine (VM) in your development environment for testing</li>
<li>Run an exact copy of the VM on the production server</li>
<li>No more surprise deployment issues</li>
<li>Simulating an entire machine can be inefficient
<ul>
<li>If you’ve ran a VM on your laptop you know how slow this can get</li>
</ul></li>
</ul>
<p>4</p>
</section>
<section id="security" class="level2">
<h2 class="anchored" data-anchor-id="security">Security</h2>
<ul>
<li>Can’t break out of the VM [Without sophisticated attacks]</li>
<li>If an attacker compromises the server, they can only access what you put in the container
<ul>
<li>Can’t “rm -rf /” your entire machine</li>
<li>Patch the exploited vulnerability and rebuild the image</li>
</ul></li>
<li>The attacker can still cause significant damage and steal private data
<ul>
<li>They just can’t destroy your server box</li>
</ul></li>
</ul>
<p>5</p>
</section>
<section id="security-1" class="level2">
<h2 class="anchored" data-anchor-id="security-1">Security</h2>
<ul>
<li>Sometimes an app has to allow code injection attacks to function
<ul>
<li>AutoLab</li>
<li>AWS</li>
<li>Digital Ocean</li>
</ul></li>
<li>Run user code in their own VM/Container</li>
</ul>
<p>6</p>
</section>
<section id="containers" class="level2">
<h2 class="anchored" data-anchor-id="containers">Containers</h2>
<ul>
<li>Effectively, lightweight VMs</li>
</ul>
<p>7</p>
</section>
<section id="docker" class="level2">
<h2 class="anchored" data-anchor-id="docker">Docker</h2>
<ul>
<li>Docker is software that’s used to create containers</li>
<li>Install Docker in your development environment to test containers</li>
<li>Install Docker in your production environment and run the same containers</li>
</ul>
<p>8</p>
</section>
<section id="dockerfile" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile">Dockerfile</h2>
<ul>
<li>To start working with Docker, write a Dockerfile</li>
<li>This file contains all the instructions needed to build a Docker image
<ul>
<li>Some similarities to a Makefile</li>
</ul></li>
</ul>
<p>9</p>
</section>
<section id="dockerfile-1" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-1">Dockerfile</h2>
<ul>
<li>Let’s explore this sample Dockerfile</li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<ul>
<li>This Dockerfile creates an image for a node.js app</li>
</ul>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<pre><code>EXPOSE 8000</code></pre>
</section>
<section id="run-the-app" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>10</p>
<section id="dockerfile-2" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-2">Dockerfile</h2>
<ul>
<li>The first line of your Dockerfile will specify the base image</li>
<li>This image is downloaded and the rest of your Dockerfile adds to this image</li>
<li>In this example: We start with Ubuntu 18.04</li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<ul>
<li>Our Dockerfile can run Linux commands in Ubunutu</li>
</ul>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-1" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>11</p>
<section id="dockerfile-3" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-3">Dockerfile</h2>
<ul>
<li>Use the RUN keyword to run commands in the base image</li>
<li>Use this for any setup of your OS before setting up your app</li>
<li>In this example: Updating apt-get which is used to install software</li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-2" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>12</p>
<section id="dockerfile-4" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-4">Dockerfile</h2>
<ul>
<li>Use ENV to set environment variables
<ul>
<li>Setting the home directory here</li>
<li>Can use ENV to setup any other variables you need</li>
</ul></li>
<li>Use WORKDIR to change your current working directory
<ul>
<li>Same as “cd”</li>
</ul></li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-3" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>13</p>
<section id="dockerfile-5" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-5">Dockerfile</h2>
<ul>
<li>Since we’re starting with a fresh image of Ubuntu:
<ul>
<li>Only the default software is installed</li>
</ul></li>
<li>RUN commands to install all required software for your app
<ul>
<li>Typically the development tools for your language of choice</li>
</ul></li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-4" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>14</p>
<section id="dockerfile-6" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-6">Dockerfile</h2>
<ul>
<li>COPY all your app file into the image</li>
<li>“.” denotes the current directory</li>
<li>Run docker from your apps root directory</li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<ul>
<li>The the first “.” will refer to your apps directory</li>
<li>We changed the home and working directory to /root</li>
</ul>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<ul>
<li>The second “.” refers to /root in the image</li>
</ul>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-5" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>15</p>
<section id="dockerfile-7" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-7">Dockerfile</h2>
<ul>
<li>Now that your apps files are in the image, run all app specific commands</li>
<li>Order is important
<ul>
<li>Don’t depend on your app files before copying them into the image</li>
</ul></li>
<li>Use RUN to install dependancies and perform any other required setup</li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-6" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>16</p>
<section id="dockerfile-8" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-8">Dockerfile</h2>
<ul>
<li>Use EXPOSE to allow specific ports to be accessed from outside the container</li>
<li>By default, all ports are blocked</li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<ul>
<li>Container is meant to run in isolation</li>
<li>To run a web app in a container, expose the port you need</li>
</ul>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-7" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>17</p>
<section id="dockerfile-9" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-9">Dockerfile</h2>
<ul>
<li>Finally, use CMD to run your app</li>
<li>Important: Do not use RUN to run your app!</li>
<li>RUN will execute the command when the image is being built</li>
<li>CMD will execute when the container is ran</li>
<li>We do not want the app to run when the image is being built</li>
</ul>
<p>FROM ubuntu:18.04</p>
<p>RUN apt-get update</p>
<pre><code>ENV HOME /root</code></pre>
<pre><code>WORKDIR /root</code></pre>
<pre><code>RUN apt-get update --fix-missing
RUN apt-get install -y nodejs
RUN apt-get install -y npm</code></pre>
<pre><code>COPY . .</code></pre>
<pre><code>RUN npm install</code></pre>
<pre><code>EXPOSE 8000</code></pre>
</section>
</section>
<section id="run-the-app-8" class="level1">
<h1>Run the app</h1>
<p>CMD node app-www.js</p>
<p>18</p>
<section id="dockerfile-10" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-10">Dockerfile</h2>
<ul>
<li>There are many base images to choose from</li>
<li>Start with an image with your language installed to simplify your docker file</li>
</ul>
<p>FROM node:13</p>
<pre><code>ENV HOME /root
WORKDIR /root</code></pre>
<p>COPY . .</p>
<ul>
<li>Search “docker <code>&lt;language&gt;</code>” to find images/tutorials for your favorite language</li>
<li>This image starts with node installed so we can remove the node installation lines</li>
</ul>
<pre><code>RUN npm install</code></pre>
<p>EXPOSE 8000</p>
<p>CMD node app-www.js</p>
<p>19</p>
</section>
<section id="dockerfile-11" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-11">Dockerfile</h2>
<ul>
<li>Example for Python</li>
</ul>
<p>FROM python:3.8</p>
<pre><code>ENV HOME /root
WORKDIR /root</code></pre>
<p>COPY . .</p>
<pre><code>RUN pip3 install -r requirements.txt</code></pre>
<p>EXPOSE 8000</p>
<p>CMD python3 -u app.py</p>
<p>20</p>
</section>
<section id="dockerfile-12" class="level2">
<h2 class="anchored" data-anchor-id="dockerfile-12">Dockerfile</h2>
<ul>
<li>For Python
<ul>
<li>Make sure you add this -u flag</li>
<li>This will force stdout and stderr to be unbuffered</li>
<li>Without it, when running in Docker, you might not see your print statements</li>
</ul></li>
</ul>
<p>FROM python:3.8</p>
<pre><code>ENV HOME /root
WORKDIR /root</code></pre>
<p>COPY . .</p>
<pre><code>RUN pip3 install -r requirements.txt</code></pre>
<p>EXPOSE 8000</p>
<p>CMD python3 -u app.py</p>
<p>21</p>
</section>
<section id="running-your-app" class="level2">
<h2 class="anchored" data-anchor-id="running-your-app">Running Your App</h2>
<ul>
<li>When preparing your app to run in a container
<ul>
<li>Do not use “localhost” [in your code]</li>
<li>Use “0.0.0.0” as the host instead</li>
<li>This allows your app to be accessed from outside the container</li>
</ul></li>
</ul>
<p>22</p>
</section>
<section id="docker-compose" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose">Docker Compose</h2>
</section>
<section id="docker-compose-1" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-1">Docker Compose</h2>
<ul>
<li>Manages building/running docker images/containers</li>
<li>Build and run with one command
<ul>
<li>docker compose up –build –force-recreate</li>
</ul></li>
<li>No need to use docker build and docker run</li>
<li>Will be used to manage multiple containers
<ul>
<li>Separate container for your database</li>
</ul></li>
<li>Let’s walk through a docker-compose.yml file</li>
</ul>
</section>
<section id="docker-compose-2" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-2">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3'
services:
app:
build: .
ports:
- '8080:8000'</code></pre>
<ul>
<li>Specify the docker compose file format version</li>
<li>Version 3[.8] is the current latest version</li>
<li>This line is now optional</li>
</ul>
</section>
<section id="docker-compose-3" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-3">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3'
services:
app:
build: .
ports:
- '8080:8000'</code></pre>
<ul>
<li>List of all the services for docker compose to run</li>
<li>A docker container is created for each service</li>
</ul>
</section>
<section id="docker-compose-4" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-4">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3'
services:
app:
build: .
ports:
- '8080:8000'</code></pre>
<ul>
<li>Name each service</li>
<li>We have one service that we name “app”</li>
<li>This name becomes the hostname when communicating between containers</li>
</ul>
</section>
<section id="docker-compose-5" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-5">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3'
services:
app:
build: .
ports:
- '8080:8000'</code></pre>
<ul>
<li>Use ‘build’ to specify the path to build from
<ul>
<li>Docker compose will look in this directory for a Dockerfile and use it to build the image</li>
</ul></li>
<li>Same as the trailing ‘.’ when building an image</li>
</ul>
</section>
<section id="docker-compose-6" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-6">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3'
services:
app:
build: .
ports:
- '8080:8000'</code></pre>
<ul>
<li>Map a local port to a container port</li>
<li>Same as using “-p 8080:8000” when running a single container</li>
</ul>
</section>
<section id="docker-compose-7" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-7">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3'
services:
app:
build: .
ports:
- '8080:8000'</code></pre>
<ul>
<li>Mapping a port allows your app [inside the container] to be accessed from your machine</li>
<li>This line maps your local port 8080 [On your machine] to port 8000 inside your container</li>
</ul>
</section>
<section id="docker-compose-8" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-8">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3'
services:
app:
build: .
ports:
- '8080:8000'</code></pre>
<p>http://localhost:8080</p>
<p>Your Laptop</p>
<p>http://app:8000</p>
<p>app</p>
<p>container</p>
<ul>
<li>When your machine receives a request for the mapped port
<ul>
<li>Docker forwards the request to the container on the specified port</li>
</ul></li>
</ul>
<p><img src="assets/slide31-diagram.png" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="running-your-app-1" class="level2">
<h2 class="anchored" data-anchor-id="running-your-app-1">Running Your App</h2>
<ul>
<li>To run your app
<ul>
<li>docker compose up</li>
</ul></li>
<li>To run in detached mode
<ul>
<li>docker compose up -d</li>
</ul></li>
<li>To rebuild and restart the containers
<ul>
<li>docker compose up –build –force-recreate</li>
<li>*This is the best command to use!</li>
</ul></li>
<li>To restart the container without rebuilding
<ul>
<li>docker compose restart</li>
</ul></li>
</ul>
</section>
<section id="running-your-app-2" class="level2">
<h2 class="anchored" data-anchor-id="running-your-app-2">Running Your App</h2>
<ul>
<li>To rebuild and restart the containers
<ul>
<li>docker compose up –build –force-recreate</li>
</ul></li>
<li>Use this command during development</li>
<li>Very important to rebuild your images after you change code
<ul>
<li>If you don’t, you will not see your changes since you’ll be running your old code</li>
</ul></li>
</ul>
</section>
<section id="docker-compose-9" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-9">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<ul>
<li>Let’s modify our docker compose configuration to run our database</li>
</ul>
</section>
<section id="docker-compose-10" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-10">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<ul>
<li>“services” is a list of all the images/ containers to create</li>
<li>We’ll add a second service for the DB</li>
</ul>
</section>
<section id="docker-compose-11" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-11">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<ul>
<li>Name each service</li>
<li>These names are used as the hostnames for each container
<ul>
<li>Used to communicate between containers</li>
</ul></li>
</ul>
<p><img src="assets/slide36-diagram.png" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="docker-compose-12" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-12">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<ul>
<li>This service named ‘mongo’ uses a pre-built image
<ul>
<li>Same as having a 1-line Dockerfile:
<ul>
<li>“FROM mongo:4.2.5”</li>
</ul></li>
</ul></li>
<li>No Dockerfile is needed</li>
</ul>
</section>
<section id="docker-compose-13" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-13">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<ul>
<li>Use ‘environment’ to set any needed environment variables</li>
<li>If using MySQL, set variables for your username/ password</li>
</ul>
</section>
<section id="docker-compose-14" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-14">Docker Compose</h2>
<p>docker-compose.yml</p>
<ul>
<li>We use an environment variable to tell our app to wait until the database is running before connecting to it</li>
</ul>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<p>FROM python:3.8.2</p>
<pre><code>ENV HOME /root
WORKDIR /root</code></pre>
<pre><code>COPY . .
RUN pip install -r requirements.txt</code></pre>
<p>EXPOSE 8000</p>
<pre><code>ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait</code></pre>
<p>CMD /wait &amp;&amp; python app.py</p>
<p><img src="assets/slide39-diagram.jpg" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="docker-compose-15" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-15">Docker Compose</h2>
<p>docker-compose.yml</p>
<ul>
<li>If the app runs before the database, it won’t be able to establish a DB connection</li>
<li>Solution: Wait for the DB to start before running the app</li>
</ul>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<p>FROM python:3.8.2</p>
<pre><code>ENV HOME /root
WORKDIR /root</code></pre>
<pre><code>COPY . .
RUN pip install -r requirements.txt</code></pre>
<p>EXPOSE 8000</p>
<pre><code>ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait</code></pre>
<p>CMD /wait &amp;&amp; python app.py</p>
<p><img src="assets/slide40-diagram.jpg" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="docker-compose-16" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-16">Docker Compose</h2>
<p>docker-compose.yml</p>
<ul>
<li>This solution from github user “ufoscout” works well</li>
</ul>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<p>FROM python:3.8.2</p>
<pre><code>ENV HOME /root
WORKDIR /root</code></pre>
<pre><code>COPY . .
RUN pip install -r requirements.txt</code></pre>
<p>EXPOSE 8000</p>
<pre><code>ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait</code></pre>
<p>CMD /wait &amp;&amp; python app.py</p>
<p><img src="assets/slide41-diagram.png" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="docker-compose-17" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-17">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<ul>
<li>This file is used to build both images and run both containers using docker-compose</li>
</ul>
</section>
<section id="docker-compose-18" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-18">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mongo:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mongo:27017
ports:
- '8080:8000'</code></pre>
<p>mongo_client = MongoClient(‘localhost’)</p>
<p>mongo_client = MongoClient(‘mongo’)</p>
<ul>
<li>Recall that we chose names for each service</li>
<li>When connecting to the database in your app
<ul>
<li>The service name is the hostname for the container</li>
</ul></li>
</ul>
<p><img src="assets/slide43-diagram.png" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="docker-compose-19" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-19">Docker Compose</h2>
<p>docker-compose.yml</p>
<ul>
<li>version: ‘3.3’ services: mongo: image: mongo:4.2.5 app: build: . environment: WAIT_HOSTS: mongo:27017 ports: - ‘8080:8000’</li>
<li>Use the name of the service</li>
<li>docker-compose will resolve this hostname to the appropriate container</li>
</ul>
<p>mongo_client = MongoClient(‘localhost’)</p>
<p>mongo_client = MongoClient(‘mongo’)</p>
<p><img src="assets/slide44-diagram.png" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="docker-compose-20" class="level2">
<h2 class="anchored" data-anchor-id="docker-compose-20">Docker Compose</h2>
<p>docker-compose.yml</p>
<pre><code>version: '3.3'
services:
mysupercooldatabase:
image: mongo:4.2.5
app:
build: .
environment:
WAIT_HOSTS: mysupercooldatabase:27017
ports:
- '8080:8000'</code></pre>
<p>mongo_client = MongoClient(‘localhost’)</p>
<p>mongo_client = MongoClient(‘mysupercooldatabase’)</p>
<ul>
<li>We can name our services whatever we want</li>
<li>Make sure you are consistent!</li>
</ul>
<p><img src="assets/slide45-diagram.png" class="img-fluid" alt="TODO: describe this image"></p>
</section>
<section id="running-your-app-3" class="level2">
<h2 class="anchored" data-anchor-id="running-your-app-3">Running Your App</h2>
<ul>
<li>docker-compose up –build –force-recreate
<ul>
<li>Will now start both containers</li>
<li>Use the service name as the host name to communicate across containers</li>
</ul></li>
</ul>


</section>
<section id="further-reading" class="level2">
<h2 class="anchored" data-anchor-id="further-reading">Further Reading</h2>
<ul>
<li><a href="https://www.docker.com/">Docker</a></li>
<li><a href="https://docs.docker.com/get-started/">Docker - Getting Started</a></li>
<li><a href="https://docs.docker.com/docker-for-windows/wsl/">Docker For Windows Users</a></li>
<li><a href="https://docs.docker.com/compose/">Docker Compose</a></li>
</ul>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>